### ISSUE TITLE
$secure is not defined

### ISSUE THREAD

**Issue by VinceG** [laravie/html#11]
- Package Version: 7.x
- Laravel Version: 8.x
- PHP Version: 7.4

### Description:

Looking at the source code
https://github.com/laravie/html/blob/7.x/src/HtmlBuilder.php#L261
https://github.com/laravie/html/blob/7.x/src/HtmlBuilder.php#L282

seems like the $secure variable is not defined but used

**Comment by crynobone** [comment]
Feel free to submit PR to fix these.

**Comment by VinceG** [comment]
@crynobone Submitted. #12

**Comment by VinceG** [comment]
@crynobone this was never tagged. what's the eta to tag a new release with this fix?
