### ISSUE TITLE
Trait Componentable missing a use statement

### ISSUE THREAD

**Issue by dvcsiky** [laravie/html#5]
When using renderComponent, it tries to return an instance that implements "Htmlable".
But since it is not aliased, an ErrorException is thrown:

> Type error: Return value of Collective\Html\FormBuilder::renderComponent() must be an instance of Collective\Html\Htmlable, instance of Illuminate\Support\HtmlString returned

After adding

`use Illuminate\Contracts\Support\Htmlable;`

into src/Componentable.php, the problem disappears as expected.

**Comment by crynobone** [comment]
Can you send a PR?

**Comment by dvcsiky** [comment]
I did.
Please bear with me, I am somewhat new to active github use, so that my first pull request went astray.

**Comment by dvcsiky** [comment]
This issue can be considered fixed.
